-- CreateEnum
CREATE TYPE "GstMode" AS ENUM ('INCLUDED', 'EXCLUDED');

-- AlterTable
ALTER TABLE "bookings" ADD COLUMN     "gstMode" "GstMode" NOT NULL DEFAULT 'EXCLUDED',
ADD COLUMN     "taxableAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "quotations" ADD COLUMN     "gstMode" "GstMode" NOT NULL DEFAULT 'EXCLUDED',
ADD COLUMN     "taxableAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "trips" ADD COLUMN     "gstMode" "GstMode" NOT NULL DEFAULT 'EXCLUDED',
ADD COLUMN     "taxableAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "vouchers" ADD COLUMN     "gstAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "gstMode" "GstMode" NOT NULL DEFAULT 'EXCLUDED',
ADD COLUMN     "gstRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxableAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalPayable" DOUBLE PRECISION;

