// ============================================================
// GK TRAVELS CRM — Supabase Database Type Definitions
//
// Normally generated by: npx supabase gen types typescript --local
// Manually maintained until Supabase CLI is available.
//
// IMPORTANT: All Insert/Update types are defined as FLAT objects.
// Do NOT use Omit<Database['public']['Tables'][...]['Row']>
// inside this file — that creates self-referential types which
// TypeScript may resolve to `never` in complex generic contexts.
// ============================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// ─── Enum types (must match Prisma schema enums) ─────────────

export type UserRole      = 'SUPER_ADMIN' | 'ADMIN' | 'MANAGER' | 'STAFF';
export type TripStatus    = 'DRAFT' | 'QUOTATION' | 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
export type LeadStatus    = 'NEW' | 'CONTACTED' | 'FOLLOW_UP' | 'QUOTATION_SENT' | 'CONFIRMED' | 'CONVERTED' | 'CANCELLED';
export type LeadPriority  = 'LOW' | 'MEDIUM' | 'HIGH';
export type BookingType   = 'FLIGHT' | 'HOTEL' | 'TRAIN' | 'BUS' | 'CAB' | 'VISA' | 'INSURANCE' | 'ACTIVITY' | 'OTHER';
export type BookingStatus = 'PENDING' | 'CONFIRMED' | 'ISSUED' | 'SUBMITTED' | 'APPROVED' | 'REJECTED' | 'CHECKED_IN' | 'DEPARTED' | 'COMPLETED' | 'CANCELLED';
export type PaymentStatus = 'PENDING' | 'RECEIVED' | 'PAID' | 'FAILED' | 'REFUNDED';
export type TaskPriority  = 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
export type TaskStatus    = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
export type DocumentCategory = 'PASSPORT' | 'VISA' | 'INSURANCE' | 'FLIGHT_TICKET' | 'HOTEL_VOUCHER' | 'PAN_CARD' | 'AADHAAR' | 'OTHER';

// ─── Row types ────────────────────────────────────────────────
// Exported separately so repositories can reference them
// without going through Database['public']['Tables'][name]['Row'].

export interface OrgRow {
  id: string; name: string; gstin: string | null; address: string | null;
  city: string | null; state: string | null; pincode: string | null;
  phone: string | null; email: string | null; website: string | null;
  logo_url: string | null; currency: string; timezone: string;
  is_active: boolean; created_at: string; updated_at: string;
}
export interface ProfileRow {
  id: string; org_id: string; name: string; email: string;
  role: UserRole; avatar: string | null; phone: string | null;
  is_active: boolean; last_login_at: string | null;
  created_at: string; updated_at: string;
}
export interface CustomerRow {
  id: string; org_id: string; name: string; phone: string;
  alt_phone: string | null; email: string | null; address: string | null;
  city: string | null; passport_no: string | null; passport_expiry: string | null;
  passport_country: string | null; pan_number: string | null;
  aadhaar_number: string | null; preferences: Json; notes: string | null;
  is_active: boolean; created_at: string; updated_at: string;
}
export interface LeadRow {
  id: string; org_id: string; customer_id: string | null;
  display_id: string; name: string; phone: string; email: string | null;
  source: string; destination: string | null; travel_date: string | null;
  return_date: string | null; pax: number; budget: string | null;
  trip_type: string | null; status: LeadStatus; priority: LeadPriority;
  notes: string | null; follow_up_date: string | null;
  assigned_to_id: string | null; created_by_id: string | null;
  converted_trip_id: string | null; converted_at: string | null;
  converted_by_id: string | null; created_at: string; updated_at: string;
}
export interface TripRow {
  id: string; org_id: string; customer_id: string | null;
  display_id: string; customer: string; phone: string; email: string | null;
  destination: string; type: string; pax: number;
  departure: string | null; return_date: string | null; status: TripStatus;
  total_amount: string | null; gst_rate: string; discount: string | null;
  gst_amount: string; total_payable: string | null; paid_amount: string;
  balance_due: string; supplier_cost: string; gross_margin: string; margin_pct: string;
  visa_status: string; hotel_status: string; flight_status: string;
  check_in_status: string; notes: string | null;
  assigned_to_id: string | null; created_by_id: string | null;
  source_lead_id: string | null; converted_at: string | null;
  converted_by_id: string | null; created_at: string; updated_at: string;
}
export interface BookingRow {
  id: string; org_id: string; trip_id: string | null;
  customer_id: string | null; display_id: string;
  type: BookingType; booking_status: BookingStatus; customer_name: string;
  selling_price: string | null; supplier_cost: string; advance: string;
  supplier_paid: string; gst_rate: string; gst_amount: string;
  total_payable: string | null; balance_due: string; supplier_pending: string;
  gross_margin: string; margin_pct: string; detail: Json; notes: string | null;
  created_at: string; updated_at: string;
}
export interface CustomerPaymentRow {
  id: string; org_id: string; trip_id: string | null;
  booking_id: string | null; customer_id: string | null;
  display_id: string; customer: string | null; amount: string;
  method: string; date: string; paid_date: string | null;
  status: PaymentStatus; reference: string | null; notes: string | null;
  created_by_id: string | null; created_at: string; updated_at: string;
}
export interface SupplierPaymentRow {
  id: string; org_id: string; trip_id: string | null;
  booking_id: string | null; display_id: string; supplier: string | null;
  amount: string; method: string; date: string; paid_date: string | null;
  status: PaymentStatus; reference: string | null; notes: string | null;
  created_at: string; updated_at: string;
}
export interface TaskRow {
  id: string; org_id: string; trip_id: string | null;
  booking_id: string | null; customer_id: string | null; title: string;
  description: string | null; priority: TaskPriority; status: TaskStatus;
  due_date: string | null; assigned_to_id: string | null;
  completed_at: string | null; created_by_id: string | null;
  created_at: string; updated_at: string;
}
export interface ActivityLogRow {
  id: string; org_id: string; type: string; message: string;
  entity_type: string; entity_id: string; user_id: string | null;
  before: Json | null; after: Json | null;
  ip_address: string | null; user_agent: string | null; created_at: string;
}
export interface TripTimelineRow {
  id: string; trip_id: string; event: string; type: string;
  user_id: string | null; created_at: string;
}
export interface DocumentRow {
  id: string; org_id: string; trip_id: string | null;
  booking_id: string | null; customer_id: string | null; name: string;
  category: DocumentCategory; storage_url: string; storage_path: string;
  mime_type: string; size: number; uploaded_by_id: string | null; created_at: string;
}

// ─── Insert types (flat — do NOT reference Row types here) ───

export interface OrgInsert {
  id?: string; name: string; gstin?: string | null; address?: string | null;
  city?: string | null; state?: string | null; pincode?: string | null;
  phone?: string | null; email?: string | null; website?: string | null;
  logo_url?: string | null; currency?: string; timezone?: string;
  is_active?: boolean; created_at?: string; updated_at?: string;
}
export interface ProfileInsert {
  id: string; org_id: string; name: string; email: string;
  role?: UserRole; avatar?: string | null; phone?: string | null;
  is_active?: boolean; last_login_at?: string | null;
  created_at?: string; updated_at?: string;
}
export interface CustomerInsert {
  id?: string; org_id: string; name: string; phone: string;
  alt_phone?: string | null; email?: string | null; address?: string | null;
  city?: string | null; passport_no?: string | null; passport_expiry?: string | null;
  passport_country?: string | null; pan_number?: string | null;
  aadhaar_number?: string | null; preferences?: Json; notes?: string | null;
  is_active?: boolean; created_at?: string; updated_at?: string;
}
export interface LeadInsert {
  id?: string; org_id: string; customer_id?: string | null;
  display_id: string; name: string; phone: string; email?: string | null;
  source: string; destination?: string | null; travel_date?: string | null;
  return_date?: string | null; pax?: number; budget?: string | null;
  trip_type?: string | null; status?: LeadStatus; priority?: LeadPriority;
  notes?: string | null; follow_up_date?: string | null;
  assigned_to_id?: string | null; created_by_id?: string | null;
  converted_trip_id?: string | null; converted_at?: string | null;
  converted_by_id?: string | null; created_at?: string; updated_at?: string;
}
export interface TripInsert {
  id?: string; org_id: string; customer_id?: string | null;
  display_id: string; customer: string; phone: string; email?: string | null;
  destination: string; type: string; pax: number;
  departure?: string | null; return_date?: string | null; status?: TripStatus;
  total_amount?: string | null; gst_rate?: string; discount?: string | null;
  gst_amount?: string; total_payable?: string | null; paid_amount?: string;
  balance_due?: string; supplier_cost?: string; gross_margin?: string; margin_pct?: string;
  visa_status?: string; hotel_status?: string; flight_status?: string;
  check_in_status?: string; notes?: string | null;
  assigned_to_id?: string | null; created_by_id?: string | null;
  source_lead_id?: string | null; converted_at?: string | null;
  converted_by_id?: string | null; created_at?: string; updated_at?: string;
}
export interface BookingInsert {
  id?: string; org_id: string; trip_id?: string | null;
  customer_id?: string | null; display_id: string;
  type: BookingType; booking_status?: BookingStatus; customer_name: string;
  selling_price?: string | null; supplier_cost?: string; advance?: string;
  supplier_paid?: string; gst_rate?: string; gst_amount?: string;
  total_payable?: string | null; balance_due?: string; supplier_pending?: string;
  gross_margin?: string; margin_pct?: string; detail?: Json; notes?: string | null;
  created_at?: string; updated_at?: string;
}
export interface CustomerPaymentInsert {
  id?: string; org_id: string; trip_id?: string | null;
  booking_id?: string | null; customer_id?: string | null;
  display_id: string; customer?: string | null; amount: string;
  method: string; date?: string; paid_date?: string | null;
  status?: PaymentStatus; reference?: string | null; notes?: string | null;
  created_by_id?: string | null; created_at?: string; updated_at?: string;
}
export interface SupplierPaymentInsert {
  id?: string; org_id: string; trip_id?: string | null;
  booking_id?: string | null; display_id: string; supplier?: string | null;
  amount: string; method: string; date?: string; paid_date?: string | null;
  status?: PaymentStatus; reference?: string | null; notes?: string | null;
  created_at?: string; updated_at?: string;
}
export interface TaskInsert {
  id?: string; org_id: string; trip_id?: string | null;
  booking_id?: string | null; customer_id?: string | null; title: string;
  description?: string | null; priority?: TaskPriority; status?: TaskStatus;
  due_date?: string | null; assigned_to_id?: string | null;
  completed_at?: string | null; created_by_id?: string | null;
  created_at?: string; updated_at?: string;
}
export interface ActivityLogInsert {
  id?: string; org_id: string; type: string; message: string;
  entity_type: string; entity_id: string; user_id?: string | null;
  before?: Json | null; after?: Json | null;
  ip_address?: string | null; user_agent?: string | null; created_at?: string;
}
export interface TripTimelineInsert {
  id?: string; trip_id: string; event: string; type?: string;
  user_id?: string | null; created_at?: string;
}
export interface DocumentInsert {
  id?: string; org_id: string; trip_id?: string | null;
  booking_id?: string | null; customer_id?: string | null; name: string;
  category: DocumentCategory; storage_url: string; storage_path: string;
  mime_type: string; size: number; uploaded_by_id?: string | null; created_at?: string;
}

// ─── Update types ─────────────────────────────────────────────

export type OrgUpdate             = Partial<OrgInsert>;
export type ProfileUpdate         = Partial<ProfileInsert>;
export type CustomerUpdate        = Partial<CustomerInsert>;
export type LeadUpdate            = Partial<LeadInsert>;
export type TripUpdate            = Partial<TripInsert>;
export type BookingUpdate         = Partial<BookingInsert>;
export type CustomerPaymentUpdate = Partial<CustomerPaymentInsert>;
export type SupplierPaymentUpdate = Partial<SupplierPaymentInsert>;
export type TaskUpdate            = Partial<TaskInsert>;
// Activity logs and timeline are immutable — no Update type needed.
export type DocumentUpdate        = Partial<DocumentInsert>;

// ─── Database interface ───────────────────────────────────────
// IMPORTANT: GenericTable (from @supabase/supabase-js) requires
//   Relationships: GenericRelationship[]
// Each table must include this field or the Supabase client resolves
// all Insert/Row types to `never` via a failing conditional type check.
// We use `never[]` because `never extends GenericRelationship` (subtype of all types),
// so `never[]` IS assignable to `GenericRelationship[]` (covariant array).
// Do NOT use `readonly []` (`as const` on an array) — it is NOT assignable
// to a mutable array type and will cause the same `never` failure.

export interface Database {
  public: {
    Tables: {
      organisations:     { Row: OrgRow;            Insert: OrgInsert;            Update: OrgUpdate;            Relationships: never[] };
      profiles:          { Row: ProfileRow;         Insert: ProfileInsert;         Update: ProfileUpdate;         Relationships: never[] };
      customers:         { Row: CustomerRow;        Insert: CustomerInsert;        Update: CustomerUpdate;        Relationships: never[] };
      leads:             { Row: LeadRow;            Insert: LeadInsert;            Update: LeadUpdate;            Relationships: never[] };
      trips:             { Row: TripRow;            Insert: TripInsert;            Update: TripUpdate;            Relationships: never[] };
      bookings:          { Row: BookingRow;         Insert: BookingInsert;         Update: BookingUpdate;         Relationships: never[] };
      customer_payments: { Row: CustomerPaymentRow; Insert: CustomerPaymentInsert; Update: CustomerPaymentUpdate; Relationships: never[] };
      supplier_payments: { Row: SupplierPaymentRow; Insert: SupplierPaymentInsert; Update: SupplierPaymentUpdate; Relationships: never[] };
      tasks:             { Row: TaskRow;            Insert: TaskInsert;            Update: TaskUpdate;            Relationships: never[] };
      activity_logs:     { Row: ActivityLogRow;     Insert: ActivityLogInsert;     Update: Partial<ActivityLogInsert>; Relationships: never[] };
      trip_timeline:     { Row: TripTimelineRow;    Insert: TripTimelineInsert;    Update: Partial<TripTimelineInsert>; Relationships: never[] };
      documents:         { Row: DocumentRow;        Insert: DocumentInsert;        Update: DocumentUpdate;        Relationships: never[] };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_org_stats: {
        Args:    { p_org_id: string };
        Returns: { trip_count: number; lead_count: number; customer_count: number; total_revenue: number; total_collected: number };
      };
      auth_org_id: {
        Args:    Record<string, never>;
        Returns: string;
      };
    };
    Enums: {
      user_role:         UserRole;
      trip_status:       TripStatus;
      lead_status:       LeadStatus;
      lead_priority:     LeadPriority;
      booking_type:      BookingType;
      booking_status:    BookingStatus;
      payment_status:    PaymentStatus;
      task_priority:     TaskPriority;
      task_status:       TaskStatus;
      document_category: DocumentCategory;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// ─── Convenience aliases ──────────────────────────────────────

export type DbOrganisation    = OrgRow;
export type DbProfile         = ProfileRow;
export type DbCustomer        = CustomerRow;
export type DbLead            = LeadRow;
export type DbTrip            = TripRow;
export type DbBooking         = BookingRow;
export type DbCustomerPayment = CustomerPaymentRow;
export type DbSupplierPayment = SupplierPaymentRow;
export type DbTask            = TaskRow;
export type DbActivityLog     = ActivityLogRow;
export type DbTripTimeline    = TripTimelineRow;
export type DbDocument        = DocumentRow;
